# Generated by Django 2.0.4 on 2018-05-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drogeria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inyectologia',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='inyectologia',
            name='nombres',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='foto',
            field=models.ImageField(upload_to='fotos/'),
        ),
    ]
