# Generated by Django 2.0.4 on 2018-05-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drogeria', '0003_auto_20180528_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inyectologia',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
